services:
  ancestralclust:
    build:
      context: .
      dockerfile: Dockerfile
    image: ancestralclust:latest
    container_name: ancestralclust
    volumes:
      # Mount a data directory for input/output files
      - ./data:/data
      # Mount current directory for development
      - .:/app
    working_dir: /app
    # Override entrypoint for interactive use
    entrypoint: []
    command: /bin/bash
    stdin_open: true
    tty: true

  # Service for running the tool directly
  ancestralclust-run:
    build:
      context: .
      dockerfile: Dockerfile
    image: ancestralclust:latest
    volumes:
      - ./data:/data
    working_dir: /app
    # Use default entrypoint (./ancestralclust)
    # Pass arguments via docker-compose run