name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: print gcc version
        run: gcc -v
      - name: build ancestralclust
        run: make
        working-directory: ./
      - name: Archive ancestralclust binary
        uses: actions/upload-artifact@v3
        with:
          name: ancestralclust
          path: ancestralclust
